extends Control
## CREDITS — and this screen is a LICENSING OBLIGATION, not a courtesy.
##
## `assets/audio/CREDITS.md` §1c records that the **Pepper Sound Pack** (Keisan /
## Fabien Boulanger) ships with a readme that asks, in writing, for credit:
##
##   > "Thanks for crediting Pepper if this pack serves you in your videos."
##
## That pack is under every melee swing, punch, kick, block, guard break, hero
## hurt, body fall, gib, dash and footstep in the game. The attribution below is
## the only thing the licence asks for, and it is free — so it is not optional,
## and it must not be quietly dropped by a future layout tidy. `PEPPER_LINE` is
## asserted verbatim by `tools/slice_test_credits.gd` for exactly that reason.
##
## Everything else here is voluntary. The Sonniss #GameAudioGDC bundle is
## explicitly royalty-free WITHOUT attribution and the OpenGameArt material is
## CC0, but the contributors are named anyway because it costs a scroll and it is
## the decent thing.
##
## ⚠ TWO PROVENANCE GAPS ARE STATED HERE RATHER THAN HIDDEN — see the "unsettled"
## section at the bottom of the roll. They are pre-existing, they are the maker's
## call, and a credits screen that pretends they do not exist is worse than one
## that says so.
##
## Reachable from the Lobby as an OVERLAY (so hosting a lobby and reading the
## credits does not drop the peer you were waiting for), and runnable as a scene
## on its own. Escape or the Back button closes it. Nothing here pauses the game.

signal closed

const TITLE_SIZE: int = 22
const HEAD_SIZE: int = 13
const BODY_SIZE: int = 11

const CHALK: Color = Color(0.93, 0.92, 0.86)
const GRAPHITE: Color = Color(0.66, 0.67, 0.74)
const HEAD_COLOR: Color = Color(0.62, 0.86, 1.0)
const WARN_COLOR: Color = Color(0.98, 0.76, 0.42)

## THE LINE THE LICENCE ASKS FOR. Do not reword, do not abbreviate, do not move
## it below the fold. Pinned by the test suite.
const PEPPER_LINE: String = "Pepper Sound Pack — Keisan (Fabien Boulanger)"

## The roll. Each entry is [kind, text]:
##   "head" — a section heading
##   "line" — a normal credit line
##   "note" — dimmer, smaller supporting text
##   "warn" — an unsettled licence the maker needs to look at
const ROLL: Array = [
	["head", "THE TOWER"],
	["note", "an unseen hand draws the floor, the mobs and the boss."],
	["note", "you are also a drawing."],

	["head", "BUILT WITH"],
	["line", "Godot Engine 4 — MIT licence, godotengine.org"],

	["head", "SOUND — ATTRIBUTION REQUESTED"],
	["line", PEPPER_LINE],
	["note", "melee, punches, kicks, blocks, guard breaks, hurts, falls, dashes, footsteps"],

	["head", "SOUND — SONNISS #GameAudioGDC BUNDLE"],
	["note", "royalty-free, attribution not required. credited anyway."],
	["line", "Alexander Kopeikin — Designed Ice · Emotion and Magic"],
	["line", "Cinematic Sound Design — Colossal Impacts · Ultra Transitions · Sci-Fi Drones"],
	["line", "Cinematic Sound Design — Cartoon Impacts · Interface & UI"],
	["line", "Federico Soler — Effective Trailer Booms · Trailer Alarms"],
	["line", "David Dumais Audio — Melee Weapons Pack 2"],
	["line", "Epic Stock Media — Humanoid Creatures · Tower Defense · Synthesized Nature"],
	["line", "Epic Stock Media — Strange Game Ambient Loops · Public Spaces"],
	["line", "CB_Sounddesign — Applicable Sounds"],
	["line", "Sonniss Ltd — sonniss.com"],

	["head", "SOUND — CC0 / PUBLIC DOMAIN (OpenGameArt)"],
	["note", "attribution not required. credited anyway."],
	["line", "BMacZero (Brian MacIntosh) — electricity"],
	["line", "faxcorp — electricity pack"],
	["line", "HaelDB — spell sounds"],
	["line", "rubberduck — 100 CC0 SFX"],
	["line", "cynicmusic — bell arpeggio"],
	["line", "JaggedStone — magic spell SFX"],

	["head", "SOUND — SYNTHESISED FOR THIS GAME"],
	["note", "no third-party material. generated by the tools in python-tools/."],
	["line", "gibberish voices · sub / rumble / crack layers · footsteps · blink · ding · holy"],

	["head", "UNSETTLED — FOR THE MAKER, NOT FOR SHIPPING"],
	["warn", "Free Fantasy SFX Pack (TomMusic) — readme states no licence terms."],
	["note", "pre-existing. capture the itch.io / gamedevmarket licence text before release."],
	["warn", "Music tracks — provenance not recorded anywhere in the repo."],
	["note", "arcadia · lord_of_the_land · for_tomorrow · unexplored_moon · combat_theme · boss_theme"],
	["note", "assets/audio/CREDITS.md §4 says the music folder was never covered. it still is not."],

	["head", ""],
	["note", "full detail: godot-project/assets/audio/CREDITS.md"],
]


func _ready() -> void:
	set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)
	# Eat taps so a stray press does not hit the lobby button underneath.
	mouse_filter = Control.MOUSE_FILTER_STOP

	var dim := ColorRect.new()
	dim.color = Color(0.03, 0.03, 0.05, 0.94)
	dim.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)
	add_child(dim)

	var margin := MarginContainer.new()
	margin.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)
	for side: String in ["left", "right"]:
		margin.add_theme_constant_override("margin_" + side, 26)
	margin.add_theme_constant_override("margin_top", 10)
	margin.add_theme_constant_override("margin_bottom", 8)
	add_child(margin)

	var col := VBoxContainer.new()
	col.add_theme_constant_override("separation", 4)
	margin.add_child(col)

	var title := Label.new()
	title.text = "CREDITS"
	title.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	title.add_theme_font_size_override("font_size", TITLE_SIZE)
	title.add_theme_color_override("font_color", CHALK)
	col.add_child(title)

	# A ScrollContainer, because the roll is longer than 360 px and a phone in
	# landscape has none of it spare. Touch drag scrolls it for free.
	var scroll := ScrollContainer.new()
	scroll.size_flags_vertical = Control.SIZE_EXPAND_FILL
	scroll.horizontal_scroll_mode = ScrollContainer.SCROLL_MODE_DISABLED
	col.add_child(scroll)

	var roll := VBoxContainer.new()
	roll.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	roll.add_theme_constant_override("separation", 2)
	scroll.add_child(roll)
	for entry: Array in ROLL:
		roll.add_child(_row(String(entry[0]), String(entry[1])))

	var back := Button.new()
	back.text = "Back"
	# ⚠ 30 -> 46 px tall. This is the ONLY control on the credits screen — the one way
	# back out of it — and at 30 px it was a 5.5 mm target on a 6.1" phone. Width stays
	# 160: it is already 29 mm, and a wide short button is missed on the axis that is
	# short. See `PauseMenu.ROW_H` for the conversion.
	back.custom_minimum_size = Vector2(160, 46)
	back.add_theme_font_size_override("font_size", 14)
	back.focus_mode = Control.FOCUS_NONE
	back.pressed.connect(close)
	var back_row := HBoxContainer.new()
	back_row.alignment = BoxContainer.ALIGNMENT_CENTER
	back_row.add_child(back)
	col.add_child(back_row)


func _unhandled_input(event: InputEvent) -> void:
	if event.is_action_pressed("ui_cancel"):
		get_viewport().set_input_as_handled()
		close()


## Emit and let the owner dispose of us. When this scene IS the root (run on its
## own), there is nobody listening, so it walks back to the Lobby itself.
func close() -> void:
	closed.emit()
	if get_tree() != null and get_tree().current_scene == self:
		get_tree().change_scene_to_file("res://scenes/ui/Lobby.tscn")


func _row(kind: String, text: String) -> Control:
	if text.is_empty():
		var pad := Control.new()
		pad.custom_minimum_size = Vector2(0, 8)
		return pad
	var l := Label.new()
	l.text = text
	l.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART
	match kind:
		"head":
			l.text = text
			l.add_theme_font_size_override("font_size", HEAD_SIZE)
			l.add_theme_color_override("font_color", HEAD_COLOR)
		"warn":
			l.text = "⚠  " + text
			l.add_theme_font_size_override("font_size", BODY_SIZE)
			l.add_theme_color_override("font_color", WARN_COLOR)
		"note":
			l.add_theme_font_size_override("font_size", BODY_SIZE - 1)
			l.add_theme_color_override("font_color", GRAPHITE)
		_:
			l.add_theme_font_size_override("font_size", BODY_SIZE)
			l.add_theme_color_override("font_color", CHALK)
	return l
